ASSET_TYPES = [
    "Server",
    "Virtual Machine",
    "Switch",
    "Router",
    "Firewall",
    "Access Point",
    "Storage",
    "Other",
]

ENVIRONMENTS = [
    "Production",
    "Staging",
    "Development",
    "Lab",
]

ASSET_STATUSES = [
    "Active",
    "Maintenance",
    "Inactive",
]


MONITORING_CHECK_TYPES = [
    "ICMP",
    "TCP",
    "HTTP",
    "HTTPS",
]

MONITORING_STATUSES = [
    "UP",
    "DOWN",
    "UNKNOWN",
]


ROLE_ADMINISTRATOR = "Administrator"
ROLE_OPERATOR = "Operator"
ROLE_VIEWER = "Viewer"

USER_ROLES = [
    ROLE_ADMINISTRATOR,
    ROLE_OPERATOR,
    ROLE_VIEWER,
]


PERMISSION_DASHBOARD_VIEW = "dashboard:view"

PERMISSION_ASSET_VIEW = "asset:view"
PERMISSION_ASSET_CREATE = "asset:create"
PERMISSION_ASSET_EDIT = "asset:edit"
PERMISSION_ASSET_DELETE = "asset:delete"

PERMISSION_MONITORING_VIEW = "monitoring:view"
PERMISSION_MONITORING_CONFIGURE = "monitoring:configure"
PERMISSION_MONITORING_RUN_CHECK = "monitoring:run_check"

PERMISSION_REPORT_VIEW = "report:view"

PERMISSION_SETTINGS_VIEW = "settings:view"

PERMISSION_USER_MANAGE = "user:manage"


ROLE_PERMISSIONS = {
    ROLE_ADMINISTRATOR: {
        PERMISSION_DASHBOARD_VIEW,
        PERMISSION_ASSET_VIEW,
        PERMISSION_ASSET_CREATE,
        PERMISSION_ASSET_EDIT,
        PERMISSION_ASSET_DELETE,
        PERMISSION_MONITORING_VIEW,
        PERMISSION_MONITORING_CONFIGURE,
        PERMISSION_MONITORING_RUN_CHECK,
        PERMISSION_REPORT_VIEW,
        PERMISSION_SETTINGS_VIEW,
        PERMISSION_USER_MANAGE,
    },

    ROLE_OPERATOR: {
        PERMISSION_DASHBOARD_VIEW,
        PERMISSION_ASSET_VIEW,
        PERMISSION_ASSET_CREATE,
        PERMISSION_ASSET_EDIT,
        PERMISSION_MONITORING_VIEW,
        PERMISSION_MONITORING_CONFIGURE,
        PERMISSION_MONITORING_RUN_CHECK,
        PERMISSION_REPORT_VIEW,
    },

    ROLE_VIEWER: {
        PERMISSION_DASHBOARD_VIEW,
        PERMISSION_ASSET_VIEW,
        PERMISSION_MONITORING_VIEW,
        PERMISSION_REPORT_VIEW,
    },
}
